'use client'

/** Analytics Navigation Configuration — grouped by user intent (Story 120.2-FE restructured) */

import {
  Package,
  Tags,
  Calendar,
  BarChart3,
  Warehouse,
  PackageSearch,
  Calculator,
  ClipboardList,
  Filter,
  ShoppingBag,
  RotateCcw,
  Search,
  Megaphone,
  Brain,
  Tag,
  Layers,
  Boxes,
  FileCheck,
  ArrowLeftRight,
  Truck,
  Bell,
  FileWarning,
  Target,
} from 'lucide-react'
import { ROUTES } from '@/lib/routes'

const RA = ROUTES.ANALYTICS

export interface NavigationItem {
  href: string
  icon: React.ComponentType<{ className?: string }>
  title: string
  description: string
  color: string
  bgColor: string
  hoverBg: string
  borderColor: string
  badge?: string
}

/** Semantic accent tones for navigation cards. Story 168.1: replaces the legacy
 *  runtime-interpolated `text-${hue}-600` classes (never generated by the Tailwind v4
 *  JIT scanner) with static semantic-token classes; hrefs/titles/descriptions/badges unchanged. */
export type NavigationTone = 'primary' | 'info' | 'success' | 'warning' | 'danger' | 'neutral'

const TONE_CLASSES: Record<
  NavigationTone,
  Pick<NavigationItem, 'color' | 'bgColor' | 'hoverBg' | 'borderColor'>
> = {
  primary: {
    color: 'text-primary',
    bgColor: 'bg-primary/10',
    hoverBg: 'hover:bg-primary/20',
    borderColor: 'border-primary/30',
  },
  info: {
    color: 'text-status-information',
    bgColor: 'bg-status-information/10',
    hoverBg: 'hover:bg-status-information/20',
    borderColor: 'border-status-information/30',
  },
  success: {
    color: 'text-status-success',
    bgColor: 'bg-status-success/10',
    hoverBg: 'hover:bg-status-success/20',
    borderColor: 'border-status-success/30',
  },
  warning: {
    color: 'text-status-warning',
    bgColor: 'bg-status-warning/10',
    hoverBg: 'hover:bg-status-warning/20',
    borderColor: 'border-status-warning/30',
  },
  danger: {
    color: 'text-status-error',
    bgColor: 'bg-status-error/10',
    hoverBg: 'hover:bg-status-error/20',
    borderColor: 'border-status-error/30',
  },
  neutral: {
    color: 'text-muted-foreground',
    bgColor: 'bg-muted',
    hoverBg: 'hover:bg-accent',
    borderColor: 'border-border',
  },
}

function nav(
  href: string,
  icon: NavigationItem['icon'],
  title: string,
  desc: string,
  tone: NavigationTone,
  badge?: string
): NavigationItem {
  return {
    href,
    icon,
    title,
    description: desc,
    badge,
    ...TONE_CLASSES[tone],
  }
}

export const analyticsNavigation = {
  financial: {
    title: 'Финансовый анализ',
    description: 'Доходы, расходы и маржинальность',
    items: [
      nav(RA.SKU, Package, 'По товарам', 'Прибыль и маржа каждого SKU', 'info'),
      nav(RA.BRAND, Tags, 'По брендам', 'Эффективность брендов', 'success'),
      nav(RA.CATEGORY, BarChart3, 'По категориям', 'Сравнение категорий', 'primary'),
      nav(RA.TIME_PERIOD, Calendar, 'По времени', 'Динамика по неделям', 'warning'),
      nav(
        RA.FINANCE_HISTORY,
        BarChart3,
        'Финансовая история',
        'P&L по неделям: прибыль, маржа, доли расходов',
        'info'
      ),
      nav(
        RA.BUYOUT_RECONCILIATION,
        FileCheck,
        'Сверка выкупов',
        'Реконсиляция выкупов и заказов',
        'info'
      ),
    ],
  },
  operational: {
    title: 'Операционная аналитика',
    description: 'Склад, поставки и затраты',
    items: [
      nav(RA.STORAGE, Warehouse, 'Хранение', 'Затраты на хранение по SKU', 'neutral'),
      nav(
        RA.SUPPLY_PLANNING,
        PackageSearch,
        'Планирование',
        'Прогноз стокаутов',
        'danger',
        'Важно'
      ),
      nav(
        RA.ORDERS,
        ClipboardList,
        'Заказы FBS',
        'Анализ заказов FBS за 365 дней',
        'warning',
        'Новое'
      ),
      nav(RA.FBS_STOCK, Boxes, 'Остатки FBS', 'Остатки на складах FBS', 'neutral'),
      nav(
        RA.FBS_ENHANCED,
        ArrowLeftRight,
        'Расширенная сверка FBS',
        'Улучшенная реконсилия FBS',
        'info'
      ),
      nav(RA.REORDER, Truck, 'Дозаказ', 'Рекомендации по дозаказу', 'warning'),
    ],
  },
  marketing: {
    title: 'Маркетинг и SEO',
    description: 'Воронка, реклама, поиск и аналитика',
    items: [
      nav(RA.FUNNEL, Filter, 'Воронка продаж', 'Просмотры → корзина → заказы → выкупы', 'info'),
      nav(RA.ADVERTISING, Megaphone, 'Реклама', 'Кампании, ROAS и эффективность', 'warning'),
      nav(RA.SEARCH, Search, 'Поисковая аналитика', 'Поисковые запросы, позиции и заказы', 'info'),
      nav(RA.BUYOUT, ShoppingBag, 'Аналитика выкупов', 'Процент выкупа и тренды по SKU', 'info'),
      nav(RA.RETURNS, RotateCcw, 'Аналитика возвратов', 'Причины возвратов и аномалии', 'danger'),
      nav(
        RA.CROSS_REFERENCE,
        Layers,
        'Кросс-анализ',
        'Поиск + реклама: пересечение и ROI',
        'primary'
      ),
    ],
  },
  strategic: {
    title: 'Стратегический анализ',
    description: 'Юнит-экономика и AI прогнозы',
    items: [
      nav(
        RA.UNIT_ECONOMICS,
        Calculator,
        'Юнит-экономика',
        'Структура затрат на единицу',
        'primary'
      ),
      nav(RA.FORECAST, Brain, 'AI Прогноз', 'Прогноз продаж на основе ML', 'primary', 'ML'),
      nav(RA.PRICING, Tag, 'Рекомендации по ценам', 'Цены для целевой маржинальности', 'success'),
      nav(RA.ALERTS, Bell, 'Оповещения', 'Управление оповещениями и уведомлениями', 'danger'),
      nav(RA.GAPS, FileWarning, 'Пропуски данных', 'Качество и полнота данных', 'warning'),
      nav(
        RA.FORECAST_ACCURACY,
        Target,
        'Точность прогнозов',
        'Метрики точности ML-моделей',
        'primary'
      ),
    ],
  },
}
