/**
 * Protected/Public route matching logic
 * Extracted from routes.ts for file size compliance.
 */

import { ROUTES } from './routes'

/**
 * Array of all protected route paths.
 * Used by middleware to determine authentication requirements.
 */
export const PROTECTED_ROUTES: readonly string[] = [
  ROUTES.DASHBOARD,
  ROUTES.COGS.ROOT,
  ROUTES.COGS.SINGLE,
  ROUTES.COGS.BULK,
  ROUTES.COGS.PRICE_CALCULATOR,
  ROUTES.ANALYTICS.ROOT,
  ROUTES.ANALYTICS.DASHBOARD,
  ROUTES.ANALYTICS.SKU,
  ROUTES.ANALYTICS.BRAND,
  ROUTES.ANALYTICS.CATEGORY,
  ROUTES.ANALYTICS.TIME_PERIOD,
  ROUTES.ANALYTICS.SUMMARY,
  ROUTES.ANALYTICS.STORAGE,
  ROUTES.ANALYTICS.SUPPLY_PLANNING,
  ROUTES.ANALYTICS.UNIT_ECONOMICS,
  ROUTES.ANALYTICS.LIQUIDITY,
  ROUTES.ANALYTICS.ADVERTISING,
  ROUTES.ANALYTICS.ORDERS,
  ROUTES.ANALYTICS.FUNNEL,
  ROUTES.ANALYTICS.BUYOUT,
  ROUTES.ANALYTICS.RETURNS,
  ROUTES.ANALYTICS.ACQUIRING,
  ROUTES.ANALYTICS.ACQUIRING_PERIOD,
  ROUTES.ANALYTICS.FBS_STOCK,
  ROUTES.ANALYTICS.FBS_ENHANCED,
  ROUTES.ANALYTICS.BUYOUT_RECONCILIATION,
  ROUTES.ANALYTICS.REORDER,
  ROUTES.ANALYTICS.SEARCH,
  ROUTES.ANALYTICS.CROSS_REFERENCE,
  ROUTES.ANALYTICS.ALERTS,
  ROUTES.ANALYTICS.GAPS,
  ROUTES.ANALYTICS.PRICING,
  ROUTES.ANALYTICS.FORECAST,
  ROUTES.ANALYTICS.FORECAST_ACCURACY,
  ROUTES.ANALYTICS.MODELS,
  ROUTES.ANALYTICS.AI_ADMIN.MODELS,
  ROUTES.ANALYTICS.AI_ADMIN.PREFERENCES,
  ROUTES.ANALYTICS.AI_ADMIN.ANOMALIES,
  ROUTES.ORDERS.ROOT,
  ROUTES.ORDERS.LIST,
  ROUTES.ORDERS.INTEGRITY,
  ROUTES.ORDERS.FBO,
  ROUTES.MONITORING,
  ROUTES.MONITOR,
  ROUTES.SHIPMENTS.ROOT,
  ROUTES.SHIPMENTS.BOX_TYPES,
  ROUTES.SHIPMENTS.SKU_PACKAGING,
  ROUTES.SUPPLIES.ROOT,
  ROUTES.SETTINGS.ROOT,
  ROUTES.SETTINGS.CABINET,
  ROUTES.SETTINGS.NOTIFICATIONS,
  ROUTES.SETTINGS.TARIFFS,
  ROUTES.SETTINGS.BACKFILL,
  ROUTES.SETTINGS.TAX,
  ROUTES.SETTINGS.EXPENSES,
] as const

/** Check if a pathname matches a protected route */
export function isProtectedRoute(pathname: string): boolean {
  return PROTECTED_ROUTES.some(path => pathname.startsWith(path))
}

/** Public routes that don't require authentication */
const PUBLIC_ROUTES: readonly string[] = [
  ROUTES.HOME,
  ROUTES.LOGIN,
  ROUTES.REGISTER,
  ROUTES.ONBOARDING.CABINET,
  ROUTES.ONBOARDING.WB_TOKEN,
  ROUTES.ONBOARDING.PROCESSING,
] as const

/** Check if a pathname matches a public route */
export function isPublicRoute(pathname: string): boolean {
  return PUBLIC_ROUTES.includes(pathname)
}
